name: Build Kivy APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Android SDK & NDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk unzip zip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          mkdir -p $HOME/cmdline-tools
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/cmdline-tools
          export ANDROID_HOME=$HOME/cmdline-tools
          export PATH=$ANDROID_HOME/bin:$PATH
          sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;25.1.8937393"

      - name: Install Buildozer & Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Clean Build Cache
        run: |
          rm -rf .buildozer bin dist

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-APK
          path: bin/*.apk
